apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: openfaas-fn
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:15-alpine
      env:
        - name: POSTGRES_PASSWORD
          value: "admin123"
        - name: POSTGRES_DB
          value: "meteo_db"
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: openfaas-fn
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
